# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'administratorFunctionality.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(705, 470)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(200, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(115, 35))
        self.label.setBaseSize(QtCore.QSize(20, 20))
        self.label.setObjectName("label")
        self.gridLayout_7.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(101, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 0, 1, 1)
        self.Home = QtWidgets.QPushButton(self.centralwidget)
        self.Home.setMinimumSize(QtCore.QSize(0, 0))
        self.Home.setMaximumSize(QtCore.QSize(95, 29))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Home.setFont(font)
        self.Home.setObjectName("Home")
        self.gridLayout_8.addWidget(self.Home, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(135, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ViewStaff = QtWidgets.QPushButton(self.centralwidget)
        self.ViewStaff.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ViewStaff.setFont(font)
        self.ViewStaff.setObjectName("ViewStaff")
        self.gridLayout_2.addWidget(self.ViewStaff, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(115, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 0, 1, 1)
        self.ViewShows = QtWidgets.QPushButton(self.centralwidget)
        self.ViewShows.setMinimumSize(QtCore.QSize(135, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ViewShows.setFont(font)
        self.ViewShows.setObjectName("ViewShows")
        self.gridLayout_5.addWidget(self.ViewShows, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_5, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ViewAnimals = QtWidgets.QPushButton(self.centralwidget)
        self.ViewAnimals.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ViewAnimals.setFont(font)
        self.ViewAnimals.setObjectName("ViewAnimals")
        self.gridLayout_3.addWidget(self.ViewAnimals, 0, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 0, 0, 1, 1)
        self.AddAnimals = QtWidgets.QPushButton(self.centralwidget)
        self.AddAnimals.setMinimumSize(QtCore.QSize(135, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.AddAnimals.setFont(font)
        self.AddAnimals.setObjectName("AddAnimals")
        self.gridLayout_6.addWidget(self.AddAnimals, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 4, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LogOut = QtWidgets.QPushButton(self.centralwidget)
        self.LogOut.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LogOut.setFont(font)
        self.LogOut.setObjectName("LogOut")
        self.gridLayout_4.addWidget(self.LogOut, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_4, 4, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem11, 5, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 119, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem12, 5, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 705, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "adminfunctionality"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">Atlanta Zoo</span></p></body></html>"))
        self.Home.setText(_translate("MainWindow", "Home"))
        self.pushButton_2.setText(_translate("MainWindow", "View Visitors"))
        self.ViewStaff.setText(_translate("MainWindow", "View Staff"))
        self.ViewShows.setText(_translate("MainWindow", "View Shows"))
        self.ViewAnimals.setText(_translate("MainWindow", "View Animals"))
        self.AddAnimals.setText(_translate("MainWindow", "Add Animals"))
        self.LogOut.setText(_translate("MainWindow", "Log out"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

