# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminviewanimals.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_adminViewAnimals(object):
    def setupUi(self, adminViewAnimals):
        adminViewAnimals.setObjectName("adminViewAnimals")
        adminViewAnimals.resize(821, 543)
        self.centralwidget = QtWidgets.QWidget(adminViewAnimals)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(5, 5, 807, 498))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Home = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.Home.setFont(font)
        self.Home.setObjectName("Home")
        self.gridLayout_3.addWidget(self.Home, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(121, 34, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 5, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(309, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 7, 1, 5)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(564, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 3, 1, 9)
        spacerItem3 = QtWidgets.QSpacerItem(51, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setMinimumSize(QtCore.QSize(90, 23))
        self.label_3.setMaximumSize(QtCore.QSize(90, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setMinimumSize(QtCore.QSize(88, 23))
        self.label_4.setMaximumSize(QtCore.QSize(88, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.species = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.species.setFont(font)
        self.species.setObjectName("species")
        self.gridLayout.addWidget(self.species, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 1, 1, 6)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(65, 28))
        self.label_2.setMaximumSize(QtCore.QSize(65, 28))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.exhibit = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.exhibit.setFont(font)
        self.exhibit.setObjectName("exhibit")
        self.exhibit.addItem("")
        self.exhibit.addItem("")
        self.exhibit.addItem("")
        self.exhibit.addItem("")
        self.exhibit.addItem("")
        self.exhibit.addItem("")
        self.gridLayout_2.addWidget(self.exhibit, 0, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setMinimumSize(QtCore.QSize(55, 23))
        self.label_5.setMaximumSize(QtCore.QSize(55, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.minAge = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.minAge.setFont(font)
        self.minAge.setObjectName("minAge")
        self.gridLayout_2.addWidget(self.minAge, 2, 1, 1, 1)
        self.maxAge = QtWidgets.QSpinBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.maxAge.setFont(font)
        self.maxAge.setObjectName("maxAge")
        self.gridLayout_2.addWidget(self.maxAge, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setMinimumSize(QtCore.QSize(57, 23))
        self.label_6.setMaximumSize(QtCore.QSize(57, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.type = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.type.setFont(font)
        self.type.setObjectName("type")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.type.addItem("")
        self.gridLayout_2.addWidget(self.type, 3, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 8, 3, 3)
        self.Search = QtWidgets.QPushButton(self.widget)
        self.Search.setMinimumSize(QtCore.QSize(95, 31))
        self.Search.setMaximumSize(QtCore.QSize(95, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.Search.setFont(font)
        self.Search.setObjectName("Search")
        self.gridLayout_3.addWidget(self.Search, 3, 1, 2, 3)
        spacerItem4 = QtWidgets.QSpacerItem(29, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 3, 11, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(52, 26, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(213, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 4, 4, 1, 4)
        spacerItem7 = QtWidgets.QSpacerItem(72, 17, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 5, 0, 1, 2)
        self.listOfAnimals = QtWidgets.QTableWidget(self.widget)
        self.listOfAnimals.setObjectName("listOfAnimals")
        self.listOfAnimals.setColumnCount(5)
        self.listOfAnimals.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.listOfAnimals.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.listOfAnimals.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.listOfAnimals.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.listOfAnimals.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.listOfAnimals.setHorizontalHeaderItem(4, item)
        self.gridLayout_3.addWidget(self.listOfAnimals, 5, 2, 2, 8)
        spacerItem8 = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 6, 10, 1, 2)
        spacerItem9 = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 7, 0, 1, 6)
        self.RemoveAnimals = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.RemoveAnimals.setFont(font)
        self.RemoveAnimals.setObjectName("RemoveAnimals")
        self.gridLayout_3.addWidget(self.RemoveAnimals, 7, 6, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(286, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 7, 9, 1, 3)
        adminViewAnimals.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(adminViewAnimals)
        self.statusbar.setObjectName("statusbar")
        adminViewAnimals.setStatusBar(self.statusbar)

        self.retranslateUi(adminViewAnimals)
        QtCore.QMetaObject.connectSlotsByName(adminViewAnimals)

    def retranslateUi(self, adminViewAnimals):
        _translate = QtCore.QCoreApplication.translate
        adminViewAnimals.setWindowTitle(_translate("adminViewAnimals", "MainWindow"))
        self.Home.setText(_translate("adminViewAnimals", "Home"))
        self.label_7.setText(_translate("adminViewAnimals", "Animals"))
        self.label.setText(_translate("adminViewAnimals", "Atlanta Zoo"))
        self.label_3.setText(_translate("adminViewAnimals", "Name:"))
        self.label_4.setText(_translate("adminViewAnimals", "Species:"))
        self.label_2.setText(_translate("adminViewAnimals", "Exhibit:"))
        self.exhibit.setItemText(0, _translate("adminViewAnimals", "All"))
        self.exhibit.setItemText(1, _translate("adminViewAnimals", "Pacific"))
        self.exhibit.setItemText(2, _translate("adminViewAnimals", "Birds"))
        self.exhibit.setItemText(3, _translate("adminViewAnimals", "Sahara"))
        self.exhibit.setItemText(4, _translate("adminViewAnimals", "Jungle"))
        self.exhibit.setItemText(5, _translate("adminViewAnimals", "Mountainous"))
        self.label_8.setText(_translate("adminViewAnimals", "Min"))
        self.label_9.setText(_translate("adminViewAnimals", "Max"))
        self.label_5.setText(_translate("adminViewAnimals", "Age:"))
        self.label_6.setText(_translate("adminViewAnimals", "Type:"))
        self.type.setItemText(0, _translate("adminViewAnimals", "All"))
        self.type.setItemText(1, _translate("adminViewAnimals", "Mammal"))
        self.type.setItemText(2, _translate("adminViewAnimals", "Bird"))
        self.type.setItemText(3, _translate("adminViewAnimals", "Amphibian"))
        self.type.setItemText(4, _translate("adminViewAnimals", "Reptile"))
        self.type.setItemText(5, _translate("adminViewAnimals", "Fish"))
        self.type.setItemText(6, _translate("adminViewAnimals", "Invertebrate"))
        self.Search.setText(_translate("adminViewAnimals", "Search"))
        item = self.listOfAnimals.horizontalHeaderItem(0)
        item.setText(_translate("adminViewAnimals", "Name"))
        item = self.listOfAnimals.horizontalHeaderItem(1)
        item.setText(_translate("adminViewAnimals", "Species"))
        item = self.listOfAnimals.horizontalHeaderItem(2)
        item.setText(_translate("adminViewAnimals", "Exhibit"))
        item = self.listOfAnimals.horizontalHeaderItem(3)
        item.setText(_translate("adminViewAnimals", "Age"))
        item = self.listOfAnimals.horizontalHeaderItem(4)
        item.setText(_translate("adminViewAnimals", "Type"))
        self.RemoveAnimals.setText(_translate("adminViewAnimals", "Remove Animals"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adminViewAnimals = QtWidgets.QMainWindow()
    ui = Ui_adminViewAnimals()
    ui.setupUi(adminViewAnimals)
    adminViewAnimals.show()
    sys.exit(app.exec_())

