# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminAddShows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(50, 120, 60, 16))
        self.label_name.setObjectName("label_name")
        self.label_date = QtWidgets.QLabel(self.centralwidget)
        self.label_date.setGeometry(QtCore.QRect(50, 250, 60, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        self.label_date.setFont(font)
        self.label_date.setObjectName("label_date")
        self.comboBox_exb = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_exb.setGeometry(QtCore.QRect(100, 160, 111, 41))
        self.comboBox_exb.setObjectName("comboBox_exb")
        self.comboBox_exb.addItem("")
        self.comboBox_exb.addItem("")
        self.comboBox_exb.addItem("")
        self.comboBox_exb.addItem("")
        self.comboBox_exb.addItem("")
        self.label_staff = QtWidgets.QLabel(self.centralwidget)
        self.label_staff.setGeometry(QtCore.QRect(50, 210, 60, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        self.label_staff.setFont(font)
        self.label_staff.setObjectName("label_staff")
        self.text_name = QtWidgets.QTextEdit(self.centralwidget)
        self.text_name.setGeometry(QtCore.QRect(100, 110, 111, 31))
        self.text_name.setObjectName("text_name")
        self.label_header = QtWidgets.QLabel(self.centralwidget)
        self.label_header.setGeometry(QtCore.QRect(340, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(22)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.comboBox_staff = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_staff.setGeometry(QtCore.QRect(90, 210, 131, 26))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.comboBox_staff.setFont(font)
        self.comboBox_staff.setObjectName("comboBox_staff")
        self.comboBox_staff.addItem("")
        self.comboBox_staff.addItem("")
        self.comboBox_staff.addItem("")
        self.button_home = QtWidgets.QPushButton(self.centralwidget)
        self.button_home.setGeometry(QtCore.QRect(10, 10, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_home.setFont(font)
        self.button_home.setObjectName("button_home")
        self.label_exb = QtWidgets.QLabel(self.centralwidget)
        self.label_exb.setGeometry(QtCore.QRect(50, 170, 60, 16))
        self.label_exb.setObjectName("label_exb")
        self.button_add_show = QtWidgets.QPushButton(self.centralwidget)
        self.button_add_show.setGeometry(QtCore.QRect(440, 170, 113, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.button_add_show.setFont(font)
        self.button_add_show.setObjectName("button_add_show")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(30, 50, 91, 16))
        self.label_title.setObjectName("label_title")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(50, 290, 60, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft Sans Serif")
        font.setPointSize(13)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(90, 250, 110, 24))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setGeometry(QtCore.QRect(90, 290, 118, 24))
        self.timeEdit.setObjectName("timeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_name.setText(_translate("MainWindow", "Name"))
        self.label_date.setText(_translate("MainWindow", "Date"))
        self.comboBox_exb.setItemText(0, _translate("MainWindow", "Pacific"))
        self.comboBox_exb.setItemText(1, _translate("MainWindow", "Jungle"))
        self.comboBox_exb.setItemText(2, _translate("MainWindow", "Sahara"))
        self.comboBox_exb.setItemText(3, _translate("MainWindow", "Mountainous"))
        self.comboBox_exb.setItemText(4, _translate("MainWindow", "Birds"))
        self.label_staff.setText(_translate("MainWindow", "Staff"))
        self.label_header.setText(_translate("MainWindow", "Add Shows"))
        self.comboBox_staff.setItemText(0, _translate("MainWindow", "martha_johnson"))
        self.comboBox_staff.setItemText(1, _translate("MainWindow", "benjamin_rao"))
        self.comboBox_staff.setItemText(2, _translate("MainWindow", "ethan_roswell"))
        self.button_home.setText(_translate("MainWindow", "Home"))
        self.label_exb.setText(_translate("MainWindow", "Exhibit"))
        self.button_add_show.setText(_translate("MainWindow", "Add Show"))
        self.label_title.setText(_translate("MainWindow", "Atlanta Zoo"))
        self.label_time.setText(_translate("MainWindow", "Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

