# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffAnimalCare.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_staffAnimalCare(object):
    def setupUi(self, staffAnimalCare):
        staffAnimalCare.setObjectName("staffAnimalCare")
        staffAnimalCare.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(staffAnimalCare)
        self.centralwidget.setObjectName("centralwidget")
        self.HomePushButton = QtWidgets.QPushButton(self.centralwidget)
        self.HomePushButton.setGeometry(QtCore.QRect(0, 0, 95, 43))
        self.HomePushButton.setMinimumSize(QtCore.QSize(95, 43))
        self.HomePushButton.setMaximumSize(QtCore.QSize(95, 43))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.HomePushButton.setFont(font)
        self.HomePushButton.setObjectName("HomePushButton")
        self.AnimalDetail = QtWidgets.QLabel(self.centralwidget)
        self.AnimalDetail.setGeometry(QtCore.QRect(270, 30, 221, 41))
        self.AnimalDetail.setMinimumSize(QtCore.QSize(221, 41))
        self.AnimalDetail.setMaximumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.AnimalDetail.setFont(font)
        self.AnimalDetail.setObjectName("AnimalDetail")
        self.AtlantaZoo = QtWidgets.QLabel(self.centralwidget)
        self.AtlantaZoo.setGeometry(QtCore.QRect(40, 80, 271, 31))
        self.AtlantaZoo.setMinimumSize(QtCore.QSize(271, 31))
        self.AtlantaZoo.setMaximumSize(QtCore.QSize(271, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.AtlantaZoo.setFont(font)
        self.AtlantaZoo.setObjectName("AtlantaZoo")
        self.NoteTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.NoteTextEdit.setGeometry(QtCore.QRect(40, 250, 536, 121))
        self.NoteTextEdit.setMinimumSize(QtCore.QSize(536, 121))
        self.NoteTextEdit.setMaximumSize(QtCore.QSize(536, 121))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.NoteTextEdit.setFont(font)
        self.NoteTextEdit.setObjectName("NoteTextEdit")
        self.LogNotesPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.LogNotesPushButton.setGeometry(QtCore.QRect(600, 280, 151, 51))
        self.LogNotesPushButton.setMinimumSize(QtCore.QSize(151, 51))
        self.LogNotesPushButton.setMaximumSize(QtCore.QSize(151, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.LogNotesPushButton.setFont(font)
        self.LogNotesPushButton.setObjectName("LogNotesPushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 380, 721, 192))
        self.tableWidget.setMinimumSize(QtCore.QSize(721, 192))
        self.tableWidget.setMaximumSize(QtCore.QSize(721, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.NameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.NameLineEdit.setGeometry(QtCore.QRect(117, 130, 119, 34))
        self.NameLineEdit.setMinimumSize(QtCore.QSize(119, 34))
        self.NameLineEdit.setMaximumSize(QtCore.QSize(119, 34))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.NameLineEdit.setFont(font)
        self.NameLineEdit.setReadOnly(True)
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.ExhibitLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.ExhibitLineEdit.setGeometry(QtCore.QRect(118, 192, 119, 34))
        self.ExhibitLineEdit.setMinimumSize(QtCore.QSize(119, 34))
        self.ExhibitLineEdit.setMaximumSize(QtCore.QSize(119, 34))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.ExhibitLineEdit.setFont(font)
        self.ExhibitLineEdit.setReadOnly(True)
        self.ExhibitLineEdit.setObjectName("ExhibitLineEdit")
        self.SpeciesLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.SpeciesLineEdit.setGeometry(QtCore.QRect(327, 131, 157, 38))
        self.SpeciesLineEdit.setMinimumSize(QtCore.QSize(157, 38))
        self.SpeciesLineEdit.setMaximumSize(QtCore.QSize(157, 38))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.SpeciesLineEdit.setFont(font)
        self.SpeciesLineEdit.setReadOnly(True)
        self.SpeciesLineEdit.setObjectName("SpeciesLineEdit")
        self.TypeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TypeLineEdit.setGeometry(QtCore.QRect(328, 189, 157, 38))
        self.TypeLineEdit.setMinimumSize(QtCore.QSize(157, 38))
        self.TypeLineEdit.setMaximumSize(QtCore.QSize(157, 38))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.TypeLineEdit.setFont(font)
        self.TypeLineEdit.setReadOnly(True)
        self.TypeLineEdit.setObjectName("TypeLineEdit")
        self.AgeLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.AgeLineEdit.setGeometry(QtCore.QRect(550, 129, 157, 38))
        self.AgeLineEdit.setMinimumSize(QtCore.QSize(157, 38))
        self.AgeLineEdit.setMaximumSize(QtCore.QSize(157, 38))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.AgeLineEdit.setFont(font)
        self.AgeLineEdit.setReadOnly(True)
        self.AgeLineEdit.setObjectName("AgeLineEdit")
        self.Species = QtWidgets.QLabel(self.centralwidget)
        self.Species.setGeometry(QtCore.QRect(239, 119, 119, 56))
        self.Species.setMinimumSize(QtCore.QSize(119, 56))
        self.Species.setMaximumSize(QtCore.QSize(119, 56))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Species.setFont(font)
        self.Species.setObjectName("Species")
        self.Type = QtWidgets.QLabel(self.centralwidget)
        self.Type.setGeometry(QtCore.QRect(265, 177, 119, 56))
        self.Type.setMinimumSize(QtCore.QSize(119, 56))
        self.Type.setMaximumSize(QtCore.QSize(119, 56))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Type.setFont(font)
        self.Type.setObjectName("Type")
        self.Age = QtWidgets.QLabel(self.centralwidget)
        self.Age.setGeometry(QtCore.QRect(494, 127, 76, 39))
        self.Age.setMinimumSize(QtCore.QSize(76, 39))
        self.Age.setMaximumSize(QtCore.QSize(76, 39))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Age.setFont(font)
        self.Age.setObjectName("Age")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(41, 121, 99, 56))
        self.Name.setMinimumSize(QtCore.QSize(99, 56))
        self.Name.setMaximumSize(QtCore.QSize(99, 56))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Name.setFont(font)
        self.Name.setObjectName("Name")
        self.Exhibit = QtWidgets.QLabel(self.centralwidget)
        self.Exhibit.setGeometry(QtCore.QRect(41, 184, 99, 56))
        self.Exhibit.setMinimumSize(QtCore.QSize(99, 56))
        self.Exhibit.setMaximumSize(QtCore.QSize(99, 56))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Exhibit.setFont(font)
        self.Exhibit.setObjectName("Exhibit")
        staffAnimalCare.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(staffAnimalCare)
        self.statusbar.setObjectName("statusbar")
        staffAnimalCare.setStatusBar(self.statusbar)

        self.retranslateUi(staffAnimalCare)
        QtCore.QMetaObject.connectSlotsByName(staffAnimalCare)

    def retranslateUi(self, staffAnimalCare):
        _translate = QtCore.QCoreApplication.translate
        staffAnimalCare.setWindowTitle(_translate("staffAnimalCare", "MainWindow"))
        self.HomePushButton.setText(_translate("staffAnimalCare", "Home"))
        self.AnimalDetail.setText(_translate("staffAnimalCare", "Animal Detail"))
        self.AtlantaZoo.setText(_translate("staffAnimalCare", "Atlanta Zoo"))
        self.LogNotesPushButton.setText(_translate("staffAnimalCare", "Log Notes"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("staffAnimalCare", "Staff Member"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("staffAnimalCare", "Note"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("staffAnimalCare", "Time"))
        self.Species.setText(_translate("staffAnimalCare", "Species:"))
        self.Type.setText(_translate("staffAnimalCare", "Type:"))
        self.Age.setText(_translate("staffAnimalCare", "Age:"))
        self.Name.setText(_translate("staffAnimalCare", "Name:"))
        self.Exhibit.setText(_translate("staffAnimalCare", "Exhibit:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    staffAnimalCare = QtWidgets.QMainWindow()
    ui = Ui_staffAnimalCare()
    ui.setupUi(staffAnimalCare)
    staffAnimalCare.show()
    sys.exit(app.exec_())

