# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitorExhibitHistory.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 836, 543))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.homeButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.gridLayout_2.addWidget(self.homeButton, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 2)
        self.exhibitHistoryLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.exhibitHistoryLabel.setFont(font)
        self.exhibitHistoryLabel.setObjectName("exhibitHistoryLabel")
        self.gridLayout_2.addWidget(self.exhibitHistoryLabel, 0, 4, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(265, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 7, 1, 2)
        self.label_title = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 1, 0, 1, 3)
        spacerItem2 = QtWidgets.QSpacerItem(652, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 1, 3, 1, 6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 25, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.nameLabel = QtWidgets.QLabel(self.widget)
        self.nameLabel.setMinimumSize(QtCore.QSize(71, 31))
        self.nameLabel.setMaximumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.gridLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.nameLineEdit = QtWidgets.QLineEdit(self.widget)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.gridLayout.addWidget(self.nameLineEdit, 0, 1, 1, 3)
        self.timeLabel = QtWidgets.QLabel(self.widget)
        self.timeLabel.setMinimumSize(QtCore.QSize(71, 31))
        self.timeLabel.setMaximumSize(QtCore.QSize(71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.gridLayout.addWidget(self.timeLabel, 0, 4, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
        self.dateTimeEdit.setMinimumSize(QtCore.QSize(201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 5, 1, 2)
        self.minLabel = QtWidgets.QLabel(self.widget)
        self.minLabel.setMinimumSize(QtCore.QSize(58, 31))
        self.minLabel.setMaximumSize(QtCore.QSize(58, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName("minLabel")
        self.gridLayout.addWidget(self.minLabel, 1, 2, 1, 1)
        self.maxLabel = QtWidgets.QLabel(self.widget)
        self.maxLabel.setMinimumSize(QtCore.QSize(61, 31))
        self.maxLabel.setMaximumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName("maxLabel")
        self.gridLayout.addWidget(self.maxLabel, 1, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(162, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 1, 4, 1, 2)
        self.dateTimeCheckBox = QtWidgets.QCheckBox(self.widget)
        self.dateTimeCheckBox.setMinimumSize(QtCore.QSize(98, 39))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.dateTimeCheckBox.setFont(font)
        self.dateTimeCheckBox.setObjectName("dateTimeCheckBox")
        self.gridLayout.addWidget(self.dateTimeCheckBox, 1, 6, 1, 1)
        self.NoVLabel = QtWidgets.QLabel(self.widget)
        self.NoVLabel.setMinimumSize(QtCore.QSize(191, 31))
        self.NoVLabel.setMaximumSize(QtCore.QSize(191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.NoVLabel.setFont(font)
        self.NoVLabel.setObjectName("NoVLabel")
        self.gridLayout.addWidget(self.NoVLabel, 2, 0, 1, 2)
        self.numVisitsMinSpinBox = QtWidgets.QSpinBox(self.widget)
        self.numVisitsMinSpinBox.setMinimumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.numVisitsMinSpinBox.setFont(font)
        self.numVisitsMinSpinBox.setObjectName("numVisitsMinSpinBox")
        self.gridLayout.addWidget(self.numVisitsMinSpinBox, 2, 2, 1, 1)
        self.numVisitsMaxSpinBox = QtWidgets.QSpinBox(self.widget)
        self.numVisitsMaxSpinBox.setMinimumSize(QtCore.QSize(61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.numVisitsMaxSpinBox.setFont(font)
        self.numVisitsMaxSpinBox.setObjectName("numVisitsMaxSpinBox")
        self.gridLayout.addWidget(self.numVisitsMaxSpinBox, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 1, 1, 7)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 8, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(308, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 4, 0, 1, 5)
        self.searchPushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(11)
        self.searchPushButton.setFont(font)
        self.searchPushButton.setObjectName("searchPushButton")
        self.gridLayout_2.addWidget(self.searchPushButton, 4, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 4, 6, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 5, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.tableWidget, 5, 1, 1, 7)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 5, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExhibitHistory"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.exhibitHistoryLabel.setText(_translate("MainWindow", "Exhibit History"))
        self.label_title.setText(_translate("MainWindow", "Atlanta Zoo"))
        self.nameLabel.setText(_translate("MainWindow", "Name:"))
        self.timeLabel.setText(_translate("MainWindow", "Time:"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy h:mm AP"))
        self.minLabel.setText(_translate("MainWindow", "Min"))
        self.maxLabel.setText(_translate("MainWindow", "Max"))
        self.dateTimeCheckBox.setText(_translate("MainWindow", "All Time"))
        self.NoVLabel.setText(_translate("MainWindow", "Number of Visits:"))
        self.searchPushButton.setText(_translate("MainWindow", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Number of Visits"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

