# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'visitorExhibitHistory.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(0, 0, 91, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.homeButton.setFont(font)
        self.homeButton.setObjectName("homeButton")
        self.exhibitHistoryLabel = QtWidgets.QLabel(self.centralwidget)
        self.exhibitHistoryLabel.setGeometry(QtCore.QRect(280, 60, 231, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        self.exhibitHistoryLabel.setFont(font)
        self.exhibitHistoryLabel.setObjectName("exhibitHistoryLabel")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(100, 140, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.NoVLabel = QtWidgets.QLabel(self.centralwidget)
        self.NoVLabel.setGeometry(QtCore.QRect(100, 210, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.NoVLabel.setFont(font)
        self.NoVLabel.setObjectName("NoVLabel")
        self.timeLabel = QtWidgets.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(430, 140, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.timeLabel.setFont(font)
        self.timeLabel.setObjectName("timeLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLineEdit.setGeometry(QtCore.QRect(200, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.searchPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchPushButton.setGeometry(QtCore.QRect(330, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.searchPushButton.setFont(font)
        self.searchPushButton.setObjectName("searchPushButton")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(500, 140, 201, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.numVisitsMinSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.numVisitsMinSpinBox.setGeometry(QtCore.QRect(370, 210, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.numVisitsMinSpinBox.setFont(font)
        self.numVisitsMinSpinBox.setObjectName("numVisitsMinSpinBox")
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setGeometry(QtCore.QRect(300, 210, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.minLabel.setFont(font)
        self.minLabel.setObjectName("minLabel")
        self.maxLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxLabel.setGeometry(QtCore.QRect(460, 210, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.maxLabel.setFont(font)
        self.maxLabel.setObjectName("maxLabel")
        self.numVisitsMaxSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.numVisitsMaxSpinBox.setGeometry(QtCore.QRect(540, 210, 61, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(12)
        self.numVisitsMaxSpinBox.setFont(font)
        self.numVisitsMaxSpinBox.setObjectName("numVisitsMaxSpinBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(62, 346, 678, 213))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.dateTimeCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.dateTimeCheckBox.setGeometry(QtCore.QRect(711, 147, 81, 20))
        self.dateTimeCheckBox.setObjectName("dateTimeCheckBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ExhibitHistory"))
        self.homeButton.setText(_translate("MainWindow", "HOME"))
        self.exhibitHistoryLabel.setText(_translate("MainWindow", "Exhibit History"))
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.NoVLabel.setText(_translate("MainWindow", "Number of Visits"))
        self.timeLabel.setText(_translate("MainWindow", "Time"))
        self.searchPushButton.setText(_translate("MainWindow", "Search"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "M/d/yyyy h:mm AP"))
        self.minLabel.setText(_translate("MainWindow", "(Min)"))
        self.maxLabel.setText(_translate("MainWindow", "(Max)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date Time"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Number of Visits"))
        self.dateTimeCheckBox.setText(_translate("MainWindow", "All Time"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

